name: Build, Test, and Deploy

on:
  push:
    branches:
      - main  # Trigger on push to main branch
  pull_request:
    branches:
      - main  # Trigger on pull request to main branch

jobs:
  build:
    runs-on: ubuntu-latest  # Use a Linux runner (you can change to windows-latest for .NET projects)

    steps:
    
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'  # Specify the Node.js version
   
    - name: Install dependencies
      run: npm install  # For Node.js, you could use dotnet restore for .NET apps

    - name: Run tests
      run: npm test  # For Node.js, use dotnet test for .NET apps

    - name: Upload test results
      uses: actions/upload-artifact@v3
      with:
        name: test-results
        path: test-results/*.xml  # Adjust path if your test results are saved elsewhere

    - name: Deploy to Azure Web App
      uses: Azure/webapps-deploy@v2
      with:
        app-name: 'your-app-name'
        slot-name: 'production'
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}  # Azure publish profile stored in secrets
        package: ./dist  # Path to your build artifact
